version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQLDB_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
    ports:
      - "3306:3306"
